spring:
  application:
    name: Inventory

  datasource:
    url: jdbc:postgresql://localhost:5432/Inventory
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    name: Inventory
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    root: INFO
  